### ISSUE TITLE
Should GroupBy provide signal output for each group?

### ISSUE THREAD

**Issue by mattdodge** [nio-blocks/mixins#15]
This type of code snippet seems to appear in a lot of the group by blocks.

```python
signals_to_notify = []
self.for_each_group(self.do_something, signals, kwargs={"to_notify": signals_to_notify})
self.notify_signals(signals_to_notify)
```

Should the group by mixin provide some kind of helper function for that? Passing the kwargs this way is sometimes confusing.

**Comment by mattdodge** [comment]
Instead, it probably makes more sense to have `for_each_group` return lists of values

**Comment by hansmosh** [comment]
Yes. We can modify the mixin so that when you use it, your self.do_something can return lists of signals. Then self.for_each_group will return one list of signals that is all the self.do_something lists combined.

Your example code snippet would become:
`self.notify_signals(self.for_each_group(self.do_something, signals))`
